### ISSUE TITLE
Another KeyError Issue -- GSSI StructureScan Mini

### ISSUE THREAD

**Issue by thekodiak13** [iannesbitt/readgssi#13]
Hey! Having some KeyError issues with my GSSI StructureScan Mini DZT files. It seems to be the same type of errors from #11 and #7. I tried installing from source and it didn't help.

<img width="1020" alt="Screen Shot 2019-06-19 at 8 32 13 PM" src="https://user-images.githubusercontent.com/52016574/59810158-fe132b00-92d1-11e9-8855-81120811265d.png">

Here are my DZT files if you need them:
[SSMini_DZT_Files.zip](https://github.com/iannesbitt/readgssi/files/3308327/SSMini_DZT_Files.zip)

Excited to continue playing with this tool. Appreciate your work!

Thanks!

**Comment by iannesbitt** [comment]
Hi @thekodiak13, thanks for attaching the code, it makes my job easy! I think this should be fixed in [de764db](https://github.com/iannesbitt/readgssi/commit/de764db64ab4dcda63795eca002fc88b477704e4). Can you check?

**Comment by iannesbitt** [comment]
Working for me:
![File____009c0G1](https://user-images.githubusercontent.com/18689918/59874563-80502d80-936c-11e9-8575-2ff806ac597c.png)

**Comment by thekodiak13** [comment]
Perfect! Working on my end as well. I really appreciate it! Great work with this project!

**Comment by thekodiak13** [comment]
Maybe not the appropriate place to ask, but is there any way to plot the DZT file with the X-axis labeling the distance scanned, and the Y-axis labeling the depth scanned?

Something like how the plot is displayed on the actual device:
![File____007](https://user-images.githubusercontent.com/52016574/59883902-8ce08000-9384-11e9-9094-20cb6e1f56c0.jpg)

No biggie if not. The plots I'm able to generate currently are already great!

**Comment by iannesbitt** [comment]
Hi @thekodiak13, I got an email that you responded with the following, although I don't see it in this thread (maybe you deleted?). I will respond anyway for completeness.

> Maybe not the appropriate place to ask, but is there any way to plot the DZT file with the X-axis labeling the distance scanned, and the Y-axis labeling the depth scanned?
>
> Something like how the plot is displayed on the actual device:
> ![image](https://user-images.githubusercontent.com/18689918/59892527-6a139300-93a7-11e9-9c40-cc0b590a615c.png)
>
> No biggie if not. The plots I'm able to generate currently are already great!

Yes! Right now it's only possible to plot distances in metric but it works. Try something like:

```bash
readgssi -x cm -z cm -p 5 -i File____009.DZT
```
![File____009c0G3](https://user-images.githubusercontent.com/18689918/59892928-12762700-93a9-11e9-9955-b2373b994bee.png)

**Comment by iannesbitt** [comment]
It looks like readgssi can't read these files' DMI wheel information correctly (#14) but I think you can get around that by specifying the correct samples per meter value with `-d 161` (back of the napkin calculations say sampling rate is ~161 traces per meter).

Out of curiosity, do you specify a samples per length value? If so what was it for these files?

**Comment by thekodiak13** [comment]
Hey @iannesbitt! Yes! I did delete because I continued playing with it and figured it out. Probably a good idea to leave it up in case others have the same question.

The samples per length was whatever the default value is. I should be able to get that information for you later today hopefully.

**Comment by iannesbitt** [comment]
Awesome. GSSI is somewhat tight-lipped on this stuff so any chance I get to test other kinds of files typically causes some strange error that ends up benefitting the program's functionality in the end. Much appreciated!

**Comment by thekodiak13** [comment]
Not sure if this is what you're looking for, but here are some of the settings I used:

Scan Density: Normal (4 scans/cm)
Dielectric: 8.0
Depth: 16in

**Comment by iannesbitt** [comment]
Ah. 4 scans per cm is actually what it read from the file (393.7 scans per meter). So it looks like I was wrong and the software was right, and you don't need to use the `-d` flag after all. My brain must have been fried last night I guess. Thanks for chasing this down anyway.

**Comment by thekodiak13** [comment]
Ha it's all good man. If you need more info on the SS Mini, let me know. I'm still learning how to use it as well.
