### ISSUE TITLE
pandas frame.append method has been removed

### ISSUE THREAD

**Issue by wmoreland** [iannesbitt/readgssi#46]
Hi, firstly - thanks for making such a great program!

I was getting the error `AttributeError: 'DataFrame' object has no attribute 'append'` when running the line
```readgssi.readgssi(infile='PROJECT_001.DZT', frmt=None, verbose=True)```

and when searching for what might be the problem came across [this stackoverflow answer](https://stackoverflow.com/a/75956237/3297523) saying that since Pandas 2.0, the frame.append method has been removed.

I've fixed my situation temporarily by downgrading to Pandas 1.5.3 and just wanted to let you know. If I get any time I'll make a pull request with the append method changed to the recommended concat method.

**Comment by iannesbitt** [comment]
Hi @wmoreland, thank you for the report and for reporting a workaround! If you can post your error output that would be really helpful. I will look for any `.append`s in the meantime.
